package:
  name: environmental-insights
  version: 0.1.0-beta

source:
  # If hosted on GitHub
  git_url: https://github.com/berrli/Environmental-Insights.git
  git_tag: v0.1.0-beta  # or use a specific commit SHA

build:
  noarch: python
  script: {{ PYTHON }} -m pip install .

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - lightgbm ==3.3.3
    - geopandas ==0.14.1
    - pandas ==2.1.3
    - scipy ==1.11.4
    - matplotlib ==3.8.2
    - overpy ==0.6
    - shapely ==2.0.2
    - pyarrow ==14.0.1
    - pyogrio ==0.7.2

test:
  imports:
    - environmental_insights

  commands:
    - insights --help

about:
  home: https://github.com/berrli/Environmental-Insights
  license: GPL-3.0
  license_family: GPL
  summary: A Python package for democratizing access to ambient air pollution data and predictive analytics.
  description: |
    Environmental Insights provides tools to access and analyze ambient air pollution data, enabling predictive analytics and insights into environmental impacts.

extra:
  recipe-maintainers:
    - berrli
