replacePollutantName = {
    "co": "CO",
    "no": "NO",
    "no2": "NO\u2082",
    "nox": "NO\u2093",
    "nv10": "NV\u2081\u2080",
    "nv25": "NV\u2082\u2085",
    "o3": "O\u2083",
    "pm10": "PM\u2081\u2080",
    "pm2p5": "PM\u2082.\u2085",
    "so2": "SO\u2082",
    "v10": "V\u2081\u2080",
    "v25": "V\u2082\u2085",
    "ch4": "CH\u2084",
}

neatFeatureVectorColumnName = {
    "Bicycle_Score": "Transport Use Bicycle Score",
    "Car_and_Taxi_Score": "Transport Use Car and Taxi Score",
    "Bus_and_Coach_Score": "Transport Use Bus and Coach Score",
    "LGV_Score": "Transport Use LGV Score",
    "HGV_Score": "Transport Use HGV Score",
    "Week_Number": "Temporal Week",
    "Month_Number": "Temporal Month",
    "Day_of_Week_Number": "Temporal Day of Week",
    "Hour_Number": "Temporal Hour",
    "U_Component_of_Wind_100m": "Meteorological  100m U Component of Wind",
    "V_Component_of_Wind_100m": "Meteorological 100m V Component of Wind",
    "U_Component_of_Wind_10m": "Meteorological 10m U Component of Wind",
    "V_Component_of_Wind_10m": "Meteorological 10m V Component of Wind",
    "Dewpoint_Temperature_2m": "Meteorological 2m Dewpoint Temperature",
    "Temperature_2m": "Meteorological 2m Temperature",
    "Boundary_Layer_Height": "Meteorological Boundary Layer Height",
    "Downward_UV_Radiation_at_the_Surface": "Meteorological Downward UV Radiation At Surface",
    "Instantaneous_10m_Wind_Gust": "Meteorological Instantaneous 10m Wind Gust",
    "Surface_Pressure": "Meteorological Surface Pressure",
    "Total_Column_Rain_Water": "Meteorological Total Column Rain Water",
    "Sentinel_5P_NO2": "Remote Sensing Sentinel 5P NO\u2082",
    "Sentinel_5P_AAI": "Remote Sensing Sentinel 5P Absorbing Aerosol Index",
    "Sentinel_5P_CO": "Remote Sensing Sentinel 5P CO",
    "Sentinel_5P_HCHO": "Remote Sensing Sentinel 5P HCHO",
    "Sentinel_5P_O3": "Remote Sensing Sentinel 5P O\u2083",
    "Road_Infrastructure_Distance_Residential": "Transport Infrastructure Distance Residential",
    "Road_Infrastructure_Distance_Footway": "Transport Infrastructure Distance Footway",
    "Road_Infrastructure_Distance_Service": "Transport Infrastructure Distance Service",
    "Road_Infrastructure_Distance_Primary": "Transport Infrastructure Distance Primary",
    "Road_Infrastructure_Distance_Path": "Transport Infrastructure Distance Path",
    "Road_Infrastructure_Distance_Cycleway": "Transport Infrastructure Distance Cycleway",
    "Road_Infrastructure_Distance_Tertiary": "Transport Infrastructure Distance Tertiary",
    "Road_Infrastructure_Distance_Secondary": "Transport Infrastructure Distance Secondary",
    "Road_Infrastructure_Distance_Unclassified": "Transport Infrastructure Distance Unclassified",
    "Road_Infrastructure_Distance_Trunk": "Transport Infrastructure Distance Trunk",
    "Road_Infrastructure_Distance_Track": "Transport Infrastructure Distance Track",
    "Road_Infrastructure_Distance_Motorway": "Transport Infrastructure Distance Motorway",
    "Road_Infrastructure_Distance_Pedestrian": "Transport Infrastructure Distance Pedestrian",
    "Road_Infrastructure_Distance_Living_Street": "Transport Infrastructure Distance Living Street",
    "Total_Length_Cycleway": "Transport Infrastructure Length Cycleway",
    "Total_Length_Footway": "Transport Infrastructure Length Footway",
    "Total_Length_Living_Street": "Transport Infrastructure Length Living Street",
    "Total_Length_Motorway": "Transport Infrastructure Length Motorway",
    "Total_Length_Path": "Transport Infrastructure Length Path",
    "Total_Length_Pedestrian": "Transport Infrastructure Length Pedestrian",
    "Total_Length_Primary": "Transport Infrastructure Length Primary",
    "Total_Length_Residential": "Transport Infrastructure Length Residential",
    "Total_Length_Secondary": "Transport Infrastructure Length Secondary",
    "Total_Length_Service": "Transport Infrastructure Length Service",
    "Total_Length_Tertiary": "Transport Infrastructure Length Tertiary",
    "Total_Length_Track": "Transport Infrastructure Length Track",
    "Total_Length_Trunk": "Transport Infrastructure Length Trunk",
    "Total_Length_Unclassified": "Transport Infrastructure Length Unclassified",
    "No_Land": "Geographical No Land",
    "Broadleaved_woodland": "Geographical Broadleaved Woodland",
    "Coniferous_Woodland": "Geographical Coniferous Woodland",
    "Arable_and_Horticulture": "Geographical Arable and Horticulture",
    "Improved_Grassland": "Geographical Improved Grassland",
    "Neutral_Grassland": "Geographical Neutral Grassland",
    "Calcareous_Grassland": "Geographical Calcareous Grassland",
    "Acid_grassland": "Geographical Acid Grassland",
    "Fen_Marsh_and_Swamp": "Geographical Fen Marsh and Swamp",
    "Heather": "Geographical Heather",
    "Heather_grassland": "Geographical Heather Grassland",
    "Bog": "Geographical Bog",
    "Inland_Rock": "Geographical Inland Rock",
    "Saltwater": "Geographical Saltwater",
    "Freshwater": "Geographical Freshwater",
    "Supralittoral_Rock": "Geographical Supra-littoral Rock",
    "Supralittoral_Sediment": "Geographical Supra-littoral Sediment",
    "Littoral_Rock": "Geographical Littoral Rock",
    "Littoral_sediment": "Geographical Littoral Sediment",
    "Saltmarsh": "Geographical Saltmarash",
    "Urban": "Geographical Urban",
    "Suburban": "Geographical Suburban",
    "NAEI_SNAP_1_NOx": "Emissions SNAP 1 NOx",
    "NAEI_SNAP_2_NOx": "Emissions SNAP 2 NOx",
    "NAEI_SNAP_3_NOx": "Emissions SNAP 3 NOx",
    "NAEI_SNAP_4_NOx": "Emissions SNAP 4 NOx",
    "NAEI_SNAP_5_NOx": "Emissions SNAP 5 NOx",
    "NAEI_SNAP_6_NOx": "Emissions SNAP 6 NOx",
    "NAEI_SNAP_7_NOx": "Emissions SNAP 7 NOx",
    "NAEI_SNAP_8_NOx": "Emissions SNAP 8 NOx",
    "NAEI_SNAP_9_NOx": "Emissions SNAP 9 NOx",
    "NAEI_SNAP_10_NOx": "Emissions SNAP 10 NOx",
    "NAEI_SNAP_11_NOx": "Emissions SNAP 11 NOx",
    "NAEI_SNAP_1_CO": "Emissions SNAP 1 CO",
    "NAEI_SNAP_2_CO": "Emissions SNAP 2 CO",
    "NAEI_SNAP_3_CO": "Emissions SNAP 3 CO",
    "NAEI_SNAP_4_CO": "Emissions SNAP 4 CO",
    "NAEI_SNAP_5_CO": "Emissions SNAP 5 CO",
    "NAEI_SNAP_6_CO": "Emissions SNAP 6 CO",
    "NAEI_SNAP_7_CO": "Emissions SNAP 7 CO",
    "NAEI_SNAP_8_CO": "Emissions SNAP 8 CO",
    "NAEI_SNAP_9_CO": "Emissions SNAP 9 CO",
    "NAEI_SNAP_10_CO": "Emissions SNAP 10 CO",
    "NAEI_SNAP_11_CO": "Emissions SNAP 11 CO",
    "NAEI_SNAP_1_SOx": "Emissions SNAP 1 SOx",
    "NAEI_SNAP_2_SOx": "Emissions SNAP 2 SOx",
    "NAEI_SNAP_3_SOx": "Emissions SNAP 3 SOx",
    "NAEI_SNAP_4_SOx": "Emissions SNAP 4 SOx",
    "NAEI_SNAP_5_SOx": "Emissions SNAP 5 SOx",
    "NAEI_SNAP_6_SOx": "Emissions SNAP 6 SOx",
    "NAEI_SNAP_7_SOx": "Emissions SNAP 7 SOx",
    "NAEI_SNAP_8_SOx": "Emissions SNAP 8 SOx",
    "NAEI_SNAP_9_SOx": "Emissions SNAP 9 SOx",
    "NAEI_SNAP_10_SOx": "Emissions SNAP 10 SOx",
    "NAEI_SNAP_11_SOx": "Emissions SNAP 11 SOx",
    "NAEI_SNAP_1_NH3": "Emissions SNAP 1 NH3",
    "NAEI_SNAP_2_NH3": "Emissions SNAP 2 NH3",
    "NAEI_SNAP_3_NH3": "Emissions SNAP 3 NH3",
    "NAEI_SNAP_4_NH3": "Emissions SNAP 4 NH3",
    "NAEI_SNAP_5_NH3": "Emissions SNAP 5 NH3",
    "NAEI_SNAP_6_NH3": "Emissions SNAP 6 NH3",
    "NAEI_SNAP_7_NH3": "Emissions SNAP 7 NH3",
    "NAEI_SNAP_8_NH3": "Emissions SNAP 8 NH3",
    "NAEI_SNAP_9_NH3": "Emissions SNAP 9 NH3",
    "NAEI_SNAP_10_NH3": "Emissions SNAP 10 NH3",
    "NAEI_SNAP_11_NH3": "Emissions SNAP 11 NH3",
    "NAEI_SNAP_1_NMVOC": "Emissions SNAP 1 NMVOC",
    "NAEI_SNAP_2_NMVOC": "Emissions SNAP 2 NMVOC",
    "NAEI_SNAP_3_NMVOC": "Emissions SNAP 3 NMVOC",
    "NAEI_SNAP_4_NMVOC": "Emissions SNAP 4 NMVOC",
    "NAEI_SNAP_5_NMVOC": "Emissions SNAP 5 NMVOC",
    "NAEI_SNAP_6_NMVOC": "Emissions SNAP 6 NMVOC",
    "NAEI_SNAP_7_NMVOC": "Emissions SNAP 7 NMVOC",
    "NAEI_SNAP_8_NMVOC": "Emissions SNAP 8 NMVOC",
    "NAEI_SNAP_9_NMVOC": "Emissions SNAP 9 NMVOC",
    "NAEI_SNAP_10_NMVOC": "Emissions SNAP 10 NMVOC",
    "NAEI_SNAP_11_NMVOC": "Emissions SNAP 11 NMVOC",
    "NAEI_SNAP_1_PM10": "Emissions SNAP 1 PM10",
    "NAEI_SNAP_2_PM10": "Emissions SNAP 2 PM10",
    "NAEI_SNAP_3_PM10": "Emissions SNAP 3 PM10",
    "NAEI_SNAP_4_PM10": "Emissions SNAP 4 PM10",
    "NAEI_SNAP_5_PM10": "Emissions SNAP 5 PM10",
    "NAEI_SNAP_6_PM10": "Emissions SNAP 6 PM10",
    "NAEI_SNAP_7_PM10": "Emissions SNAP 7 PM10",
    "NAEI_SNAP_8_PM10": "Emissions SNAP 8 PM10",
    "NAEI_SNAP_9_PM10": "Emissions SNAP 9 PM10",
    "NAEI_SNAP_10_PM10": "Emissions SNAP 10 PM10",
    "NAEI_SNAP_11_PM10": "Emissions SNAP 11 PM10",
    "NAEI_SNAP_1_PM25": "Emissions SNAP 1 PM25",
    "NAEI_SNAP_2_PM25": "Emissions SNAP 2 PM25",
    "NAEI_SNAP_3_PM25": "Emissions SNAP 3 PM25",
    "NAEI_SNAP_4_PM25": "Emissions SNAP 4 PM25",
    "NAEI_SNAP_5_PM25": "Emissions SNAP 5 PM25",
    "NAEI_SNAP_6_PM25": "Emissions SNAP 6 PM25",
    "NAEI_SNAP_7_PM25": "Emissions SNAP 7 PM25",
    "NAEI_SNAP_8_PM25": "Emissions SNAP 8 PM25",
    "NAEI_SNAP_9_PM25": "Emissions SNAP 9 PM25",
    "NAEI_SNAP_10_PM25": "Emissions SNAP 10 PM25",
    "NAEI_SNAP_11_PM25": "Emissions SNAP 11 PM25",
}

neatFeatureVectorColumnNameShort = {
    "Bicycle_Score": "TU Bicycle Score",
    "Car_and_Taxi_Score": "TU Car and Taxi Score",
    "Bus_and_Coach_Score": "TU Bus and Coach Score",
    "LGV_Score": "TU LGV Score",
    "HGV_Score": "TU HGV Score",
    "Week_Number": "T Week",
    "Month_Number": "T Month",
    "Day_of_Week_Number": "T Day of Week",
    "Hour_Number": "T Hour",
    "U_Component_of_Wind_100m": "M 100m U Component of Wind",
    "V_Component_of_Wind_100m": "M 100m V Component of Wind",
    "U_Component_of_Wind_10m": "M 10m U Component of Wind",
    "V_Component_of_Wind_10m": "M 10m V Component of Wind",
    "Dewpoint_Temperature_2m": "M 2m Dewpoint Temperature",
    "Temperature_2m": "M 2m Temperature",
    "Boundary_Layer_Height": "M Boundary Layer Height",
    "Downward_UV_Radiation_at_the_Surface": "M Downward UV Radiation At Surface",
    "Instantaneous_10m_Wind_Gust": "M Instantaneous 10m Wind Gust",
    "Surface_Pressure": "M Surface Pressure",
    "Total_Column_Rain_Water": "M Total Column Rain Water",
    "Sentinel_5P_NO2": "RS Sentinel 5P NO₂",
    "Sentinel_5P_AAI": "RS Sentinel 5P Absorbing Aerosol Index",
    "Sentinel_5P_CO": "RS Sentinel 5P CO",
    "Sentinel_5P_HCHO": "RS Sentinel 5P HCHO",
    "Sentinel_5P_O3": "RS Sentinel 5P O₃",
    "Road_Infrastructure_Distance_Residential": "TI Distance Residential",
    "Road_Infrastructure_Distance_Footway": "TI Distance Footway",
    "Road_Infrastructure_Distance_Service": "TI Distance Service",
    "Road_Infrastructure_Distance_Primary": "TI Distance Primary",
    "Road_Infrastructure_Distance_Path": "TI Distance Path",
    "Road_Infrastructure_Distance_Cycleway": "TI Distance Cycleway",
    "Road_Infrastructure_Distance_Tertiary": "TI Distance Tertiary",
    "Road_Infrastructure_Distance_Secondary": "TI Distance Secondary",
    "Road_Infrastructure_Distance_Unclassified": "TI Distance Unclassified",
    "Road_Infrastructure_Distance_Trunk": "TI Distance Trunk",
    "Road_Infrastructure_Distance_Track": "TI Distance Track",
    "Road_Infrastructure_Distance_Motorway": "TI Distance Motorway",
    "Road_Infrastructure_Distance_Pedestrian": "TI Distance Pedestrian",
    "Road_Infrastructure_Distance_Living_Street": "TI Distance Living Street",
    "Total_Length_Cycleway": "TI Length Cycleway",
    "Total_Length_Footway": "TI Length Footway",
    "Total_Length_Living_Street": "TI Length Living Street",
    "Total_Length_Motorway": "TI Length Motorway",
    "Total_Length_Path": "TI Length Path",
    "Total_Length_Pedestrian": "TI Length Pedestrian",
    "Total_Length_Primary": "TI Length Primary",
    "Total_Length_Residential": "TI Length Residential",
    "Total_Length_Secondary": "TI Length Secondary",
    "Total_Length_Service": "TI Length Service",
    "Total_Length_Tertiary": "TI Length Tertiary",
    "Total_Length_Track": "TI Length Track",
    "Total_Length_Trunk": "TI Length Trunk",
    "Total_Length_Unclassified": "TI Length Unclassified",
    "No_Land": "G No Land",
    "Broadleaved_woodland": "G Broadleaved Woodland",
    "Coniferous_Woodland": "G Coniferous Woodland",
    "Arable_and_Horticulture": "G Arable and Horticulture",
    "Improved_Grassland": "G Improved Grassland",
    "Neutral_Grassland": "G Neutral Grassland",
    "Calcareous_Grassland": "G Calcareous Grassland",
    "Acid_grassland": "G Acid Grassland",
    "Fen_Marsh_and_Swamp": "G Fen Marsh and Swamp",
    "Heather": "G Heather",
    "Heather_grassland": "G Heather Grassland",
    "Bog": "G Bog",
    "Inland_Rock": "G Inland Rock",
    "Saltwater": "G Saltwater",
    "Freshwater": "G Freshwater",
    "Supralittoral_Rock": "G Supra-littoral Rock",
    "Supralittoral_Sediment": "G Supra-littoral Sediment",
    "Littoral_Rock": "G Littoral Rock",
    "Littoral_sediment": "G Littoral Sediment",
    "Saltmarsh": "G Saltmarash",
    "Urban": "G Urban",
    "Suburban": "G Suburban",
    "NAEI_SNAP_1_NOx": "E SNAP 1 NOx",
    "NAEI_SNAP_1_CO": "E SNAP 1 CO",
    "NAEI_SNAP_1_SOx": "E SNAP 1 SOx",
    "NAEI_SNAP_1_NH3": "E SNAP 1 NH3",
    "NAEI_SNAP_1_NMVOC": "E SNAP 1 NMVOC",
    "NAEI_SNAP_1_PM10": "E SNAP 1 PM10",
    "NAEI_SNAP_1_PM25": "E SNAP 1 PM25",
    "NAEI_SNAP_2_NOx": "E SNAP 2 NOx",
    "NAEI_SNAP_2_CO": "E SNAP 2 CO",
    "NAEI_SNAP_2_SOx": "E SNAP 2 SOx",
    "NAEI_SNAP_2_NH3": "E SNAP 2 NH3",
    "NAEI_SNAP_2_NMVOC": "E SNAP 2 NMVOC",
    "NAEI_SNAP_2_PM10": "E SNAP 2 PM10",
    "NAEI_SNAP_2_PM25": "E SNAP 2 PM25",
    "NAEI_SNAP_3_NOx": "E SNAP 3 NOx",
    "NAEI_SNAP_3_CO": "E SNAP 3 CO",
    "NAEI_SNAP_3_SOx": "E SNAP 3 SOx",
    "NAEI_SNAP_3_NH3": "E SNAP 3 NH3",
    "NAEI_SNAP_3_NMVOC": "E SNAP 3 NMVOC",
    "NAEI_SNAP_3_PM10": "E SNAP 3 PM10",
    "NAEI_SNAP_3_PM25": "E SNAP 3 PM25",
    "NAEI_SNAP_4_NOx": "E SNAP 4 NOx",
    "NAEI_SNAP_4_CO": "E SNAP 4 CO",
    "NAEI_SNAP_4_SOx": "E SNAP 4 SOx",
    "NAEI_SNAP_4_NH3": "E SNAP 4 NH3",
    "NAEI_SNAP_4_NMVOC": "E SNAP 4 NMVOC",
    "NAEI_SNAP_4_PM10": "E SNAP 4 PM10",
    "NAEI_SNAP_4_PM25": "E SNAP 4 PM25",
    "NAEI_SNAP_5_NOx": "E SNAP 5 NOx",
    "NAEI_SNAP_5_CO": "E SNAP 5 CO",
    "NAEI_SNAP_5_SOx": "E SNAP 5 SOx",
    "NAEI_SNAP_5_NH3": "E SNAP 5 NH3",
    "NAEI_SNAP_5_NMVOC": "E SNAP 5 NMVOC",
    "NAEI_SNAP_5_PM10": "E SNAP 5 PM10",
    "NAEI_SNAP_5_PM25": "E SNAP 5 PM25",
    "NAEI_SNAP_6_NOx": "E SNAP 6 NOx",
    "NAEI_SNAP_6_CO": "E SNAP 6 CO",
    "NAEI_SNAP_6_SOx": "E SNAP 6 SOx",
    "NAEI_SNAP_6_NH3": "E SNAP 6 NH3",
    "NAEI_SNAP_6_NMVOC": "E SNAP 6 NMVOC",
    "NAEI_SNAP_6_PM10": "E SNAP 6 PM10",
    "NAEI_SNAP_6_PM25": "E SNAP 6 PM25",
    "NAEI_SNAP_7_NOx": "E SNAP 7 NOx",
    "NAEI_SNAP_7_CO": "E SNAP 7 CO",
    "NAEI_SNAP_7_SOx": "E SNAP 7 SOx",
    "NAEI_SNAP_7_NH3": "E SNAP 7 NH3",
    "NAEI_SNAP_7_NMVOC": "E SNAP 7 NMVOC",
    "NAEI_SNAP_7_PM10": "E SNAP 7 PM10",
    "NAEI_SNAP_7_PM25": "E SNAP 7 PM25",
    "NAEI_SNAP_8_NOx": "E SNAP 8 NOx",
    "NAEI_SNAP_8_CO": "E SNAP 8 CO",
    "NAEI_SNAP_8_SOx": "E SNAP 8 SOx",
    "NAEI_SNAP_8_NH3": "E SNAP 8 NH3",
    "NAEI_SNAP_8_NMVOC": "E SNAP 8 NMVOC",
    "NAEI_SNAP_8_PM10": "E SNAP 8 PM10",
    "NAEI_SNAP_8_PM25": "E SNAP 8 PM25",
    "NAEI_SNAP_9_NOx": "E SNAP 9 NOx",
    "NAEI_SNAP_9_CO": "E SNAP 9 CO",
    "NAEI_SNAP_9_SOx": "E SNAP 9 SOx",
    "NAEI_SNAP_9_NH3": "E SNAP 9 NH3",
    "NAEI_SNAP_9_NMVOC": "E SNAP 9 NMVOC",
    "NAEI_SNAP_9_PM10": "E SNAP 9 PM10",
    "NAEI_SNAP_9_PM25": "E SNAP 9 PM25",
    "NAEI_SNAP_10_NOx": "E SNAP 10 NOx",
    "NAEI_SNAP_10_CO": "E SNAP 10 CO",
    "NAEI_SNAP_10_SOx": "E SNAP 10 SOx",
    "NAEI_SNAP_10_NH3": "E SNAP 10 NH3",
    "NAEI_SNAP_10_NMVOC": "E SNAP 10 NMVOC",
    "NAEI_SNAP_10_PM10": "E SNAP 10 PM10",
    "NAEI_SNAP_10_PM25": "E SNAP 10 PM25",
    "NAEI_SNAP_11_NOx": "E SNAP 11 NOx",
    "NAEI_SNAP_11_CO": "E SNAP 11 CO",
    "NAEI_SNAP_11_SOx": "E SNAP 11 SOx",
    "NAEI_SNAP_11_NH3": "E SNAP 11 NH3",
    "NAEI_SNAP_11_NMVOC": "E SNAP 11 NMVOC",
    "NAEI_SNAP_11_PM10": "E SNAP 11 PM10",
    "NAEI_SNAP_11_PM25": "E SNAP 11 PM25",
}



featureVectorColumnNames = [
    "Bicycle_Score",
    "Car_and_Taxi_Score",
    "Bus_and_Coach_Score",
    "LGV_Score",
    "HGV_Score",
    "Week_Number",
    "Month_Number",
    "Day_of_Week_Number",
    "Hour_Number",
    "U_Component_of_Wind_100m",
    "V_Component_of_Wind_100m",
    "U_Component_of_Wind_10m",
    "V_Component_of_Wind_10m",
    "Dewpoint_Temperature_2m",
    "Temperature_2m",
    "Boundary_Layer_Height",
    "Downward_UV_Radiation_at_the_Surface",
    "Instantaneous_10m_Wind_Gust",
    "Surface_Pressure",
    "Total_Column_Rain_Water",
    "Sentinel_5P_NO2",
    "Sentinel_5P_AAI",
    "Sentinel_5P_CO",
    "Sentinel_5P_HCHO",
    "Sentinel_5P_O3",
    "Road_Infrastructure_Distance_Residential",
    "Road_Infrastructure_Distance_Footway",
    "Road_Infrastructure_Distance_Service",
    "Road_Infrastructure_Distance_Primary",
    "Road_Infrastructure_Distance_Path",
    "Road_Infrastructure_Distance_Cycleway",
    "Road_Infrastructure_Distance_Tertiary",
    "Road_Infrastructure_Distance_Secondary",
    "Road_Infrastructure_Distance_Unclassified",
    "Road_Infrastructure_Distance_Trunk",
    "Road_Infrastructure_Distance_Track",
    "Road_Infrastructure_Distance_Motorway",
    "Road_Infrastructure_Distance_Pedestrian",
    "Road_Infrastructure_Distance_Living_Street",
    "Total_Length_Cycleway",
    "Total_Length_Footway",
    "Total_Length_Living_Street",
    "Total_Length_Motorway",
    "Total_Length_Path",
    "Total_Length_Pedestrian",
    "Total_Length_Primary",
    "Total_Length_Residential",
    "Total_Length_Secondary",
    "Total_Length_Service",
    "Total_Length_Tertiary",
    "Total_Length_Track",
    "Total_Length_Trunk",
    "Total_Length_Unclassified",
    "No_Land",
    "Broadleaved_woodland",
    "Coniferous_Woodland",
    "Arable_and_Horticulture",
    "Improved_Grassland",
    "Neutral_Grassland",
    "Calcareous_Grassland",
    "Acid_grassland",
    "Fen_Marsh_and_Swamp",
    "Heather",
    "Heather_grassland",
    "Bog",
    "Inland_Rock",
    "Saltwater",
    "Freshwater",
    "Supralittoral_Rock",
    "Supralittoral_Sediment",
    "Littoral_Rock",
    "Littoral_sediment",
    "Saltmarsh",
    "Urban",
    "Suburban",
    "NAEI_SNAP_1_NOx",
    "NAEI_SNAP_1_CO",
    "NAEI_SNAP_1_SOx",
    "NAEI_SNAP_1_NH3",
    "NAEI_SNAP_1_NMVOC",
    "NAEI_SNAP_1_PM10",
    "NAEI_SNAP_1_PM25",
    "NAEI_SNAP_2_NOx",
    "NAEI_SNAP_2_CO",
    "NAEI_SNAP_2_SOx",
    "NAEI_SNAP_2_NH3",
    "NAEI_SNAP_2_NMVOC",
    "NAEI_SNAP_2_PM10",
    "NAEI_SNAP_2_PM25",
    "NAEI_SNAP_3_NOx",
    "NAEI_SNAP_3_CO",
    "NAEI_SNAP_3_SOx",
    "NAEI_SNAP_3_NH3",
    "NAEI_SNAP_3_NMVOC",
    "NAEI_SNAP_3_PM10",
    "NAEI_SNAP_3_PM25",
    "NAEI_SNAP_4_NOx",
    "NAEI_SNAP_4_CO",
    "NAEI_SNAP_4_SOx",
    "NAEI_SNAP_4_NH3",
    "NAEI_SNAP_4_NMVOC",
    "NAEI_SNAP_4_PM10",
    "NAEI_SNAP_4_PM25",
    "NAEI_SNAP_5_NOx",
    "NAEI_SNAP_5_CO",
    "NAEI_SNAP_5_SOx",
    "NAEI_SNAP_5_NH3",
    "NAEI_SNAP_5_NMVOC",
    "NAEI_SNAP_5_PM10",
    "NAEI_SNAP_5_PM25",
    "NAEI_SNAP_6_NOx",
    "NAEI_SNAP_6_CO",
    "NAEI_SNAP_6_SOx",
    "NAEI_SNAP_6_NH3",
    "NAEI_SNAP_6_NMVOC",
    "NAEI_SNAP_6_PM10",
    "NAEI_SNAP_6_PM25",
    "NAEI_SNAP_7_NOx",
    "NAEI_SNAP_7_CO",
    "NAEI_SNAP_7_SOx",
    "NAEI_SNAP_7_NH3",
    "NAEI_SNAP_7_NMVOC",
    "NAEI_SNAP_7_PM10",
    "NAEI_SNAP_7_PM25",
    "NAEI_SNAP_8_NOx",
    "NAEI_SNAP_8_CO",
    "NAEI_SNAP_8_SOx",
    "NAEI_SNAP_8_NH3",
    "NAEI_SNAP_8_NMVOC",
    "NAEI_SNAP_8_PM10",
    "NAEI_SNAP_8_PM25",
    "NAEI_SNAP_9_NOx",
    "NAEI_SNAP_9_CO",
    "NAEI_SNAP_9_SOx",
    "NAEI_SNAP_9_NH3",
    "NAEI_SNAP_9_NMVOC",
    "NAEI_SNAP_9_PM10",
    "NAEI_SNAP_9_PM25",
    "NAEI_SNAP_10_NOx",
    "NAEI_SNAP_10_CO",
    "NAEI_SNAP_10_SOx",
    "NAEI_SNAP_10_NH3",
    "NAEI_SNAP_10_NMVOC",
    "NAEI_SNAP_10_PM10",
    "NAEI_SNAP_10_PM25",
    "NAEI_SNAP_11_NOx",
    "NAEI_SNAP_11_CO",
    "NAEI_SNAP_11_SOx",
    "NAEI_SNAP_11_NH3",
    "NAEI_SNAP_11_NMVOC",
    "NAEI_SNAP_11_PM10",
    "NAEI_SNAP_11_PM25",
]

featureVectorDatasetFamily = {
    "Bicycle_Score": "Transport Use",
    "Car_and_Taxi_Score": "Transport Use",
    "Bus_and_Coach_Score": "Transport Use",
    "LGV_Score": "Transport Use",
    "HGV_Score": "Transport Use",
    "Week_Number": "Temporal",
    "Month_Number": "Temporal",
    "Day_of_Week_Number": "Temporal",
    "Hour_Number": "Temporal",
    "U_Component_of_Wind_100m": "Metrological",
    "V_Component_of_Wind_100m": "Metrological",
    "U_Component_of_Wind_10m": "Metrological",
    "V_Component_of_Wind_10m": "Metrological",
    "Dewpoint_Temperature_2m": "Metrological",
    "Temperature_2m": "Metrological",
    "Boundary_Layer_Height": "Metrological",
    "Downward_UV_Radiation_at_the_Surface": "Metrological",
    "Instantaneous_10m_Wind_Gust": "Metrological",
    "Surface_Pressure": "Metrological",
    "Total_Column_Rain_Water": "Metrological",
    "Sentinel_5P_NO2": "Remote Sensing",
    "Sentinel_5P_AAI": "Remote Sensing",
    "Sentinel_5P_CO": "Remote Sensing",
    "Sentinel_5P_HCHO": "Remote Sensing",
    "Sentinel_5P_O3": "Remote Sensing",
    "Road_Infrastructure_Distance_Residential": "Transport Infrastructure",
    "Road_Infrastructure_Distance_Footway": "Transport Infrastructure",
    "Road_Infrastructure_Distance_Service": "Transport Infrastructure",
    "Road_Infrastructure_Distance_Primary": "Transport Infrastructure",
    "Road_Infrastructure_Distance_Path": "Transport Infrastructure",
    "Road_Infrastructure_Distance_Cycleway": "Transport Infrastructure",
    "Road_Infrastructure_Distance_Tertiary": "Transport Infrastructure",
    "Road_Infrastructure_Distance_Secondary": "Transport Infrastructure",
    "Road_Infrastructure_Distance_Unclassified": "Transport Infrastructure",
    "Road_Infrastructure_Distance_Trunk": "Transport Infrastructure",
    "Road_Infrastructure_Distance_Track": "Transport Infrastructure",
    "Road_Infrastructure_Distance_Motorway": "Transport Infrastructure",
    "Road_Infrastructure_Distance_Pedestrian": "Transport Infrastructure",
    "Road_Infrastructure_Distance_Living_Street": "Transport Infrastructure",
    "Total_Length_Cycleway": "Transport Infrastructure",
    "Total_Length_Footway": "Transport Infrastructure",
    "Total_Length_Living_Street": "Transport Infrastructure",
    "Total_Length_Motorway": "Transport Infrastructure",
    "Total_Length_Path": "Transport Infrastructure",
    "Total_Length_Pedestrian": "Transport Infrastructure",
    "Total_Length_Primary": "Transport Infrastructure",
    "Total_Length_Residential": "Transport Infrastructure",
    "Total_Length_Secondary": "Transport Infrastructure",
    "Total_Length_Service": "Transport Infrastructure",
    "Total_Length_Tertiary": "Transport Infrastructure",
    "Total_Length_Track": "Transport Infrastructure",
    "Total_Length_Trunk": "Transport Infrastructure",
    "Total_Length_Unclassified": "Transport Infrastructure",
    "No_Land": "Geographic",
    "Broadleaved_woodland": "Geographic",
    "Coniferous_Woodland": "Geographic",
    "Arable_and_Horticulture": "Geographic",
    "Improved_Grassland": "Geographic",
    "Neutral_Grassland": "Geographic",
    "Calcareous_Grassland": "Geographic",
    "Acid_grassland": "Geographic",
    "Fen_Marsh_and_Swamp": "Geographic",
    "Heather": "Geographic",
    "Heather_grassland": "Geographic",
    "Bog": "Geographic",
    "Inland_Rock": "Geographic",
    "Saltwater": "Geographic",
    "Freshwater": "Geographic",
    "Supralittoral_Rock": "Geographic",
    "Supralittoral_Sediment": "Geographic",
    "Littoral_Rock": "Geographic",
    "Littoral_sediment": "Geographic",
    "Saltmarsh": "Geographic",
    "Urban": "Geographic",
    "Suburban": "Geographic",
    "NAEI_SNAP_1_NOx": "Emissions",
    "NAEI_SNAP_2_NOx": "Emissions",
    "NAEI_SNAP_3_NOx": "Emissions",
    "NAEI_SNAP_4_NOx": "Emissions",
    "NAEI_SNAP_5_NOx": "Emissions",
    "NAEI_SNAP_6_NOx": "Emissions",
    "NAEI_SNAP_7_NOx": "Emissions",
    "NAEI_SNAP_8_NOx": "Emissions",
    "NAEI_SNAP_9_NOx": "Emissions",
    "NAEI_SNAP_10_NOx": "Emissions",
    "NAEI_SNAP_11_NOx": "Emissions",
    "NAEI_SNAP_1_CO": "Emissions",
    "NAEI_SNAP_2_CO": "Emissions",
    "NAEI_SNAP_3_CO": "Emissions",
    "NAEI_SNAP_4_CO": "Emissions",
    "NAEI_SNAP_5_CO": "Emissions",
    "NAEI_SNAP_6_CO": "Emissions",
    "NAEI_SNAP_7_CO": "Emissions",
    "NAEI_SNAP_8_CO": "Emissions",
    "NAEI_SNAP_9_CO": "Emissions",
    "NAEI_SNAP_10_CO": "Emissions",
    "NAEI_SNAP_11_CO": "Emissions",
    "NAEI_SNAP_1_SOx": "Emissions",
    "NAEI_SNAP_2_SOx": "Emissions",
    "NAEI_SNAP_3_SOx": "Emissions",
    "NAEI_SNAP_4_SOx": "Emissions",
    "NAEI_SNAP_5_SOx": "Emissions",
    "NAEI_SNAP_6_SOx": "Emissions",
    "NAEI_SNAP_7_SOx": "Emissions",
    "NAEI_SNAP_8_SOx": "Emissions",
    "NAEI_SNAP_9_SOx": "Emissions",
    "NAEI_SNAP_10_SOx": "Emissions",
    "NAEI_SNAP_11_SOx": "Emissions",
    "NAEI_SNAP_1_NH3": "Emissions",
    "NAEI_SNAP_2_NH3": "Emissions",
    "NAEI_SNAP_3_NH3": "Emissions",
    "NAEI_SNAP_4_NH3": "Emissions",
    "NAEI_SNAP_5_NH3": "Emissions",
    "NAEI_SNAP_6_NH3": "Emissions",
    "NAEI_SNAP_7_NH3": "Emissions",
    "NAEI_SNAP_8_NH3": "Emissions",
    "NAEI_SNAP_9_NH3": "Emissions",
    "NAEI_SNAP_10_NH3": "Emissions",
    "NAEI_SNAP_11_NH3": "Emissions",
    "NAEI_SNAP_1_NMVOC": "Emissions",
    "NAEI_SNAP_2_NMVOC": "Emissions",
    "NAEI_SNAP_3_NMVOC": "Emissions",
    "NAEI_SNAP_4_NMVOC": "Emissions",
    "NAEI_SNAP_5_NMVOC": "Emissions",
    "NAEI_SNAP_6_NMVOC": "Emissions",
    "NAEI_SNAP_7_NMVOC": "Emissions",
    "NAEI_SNAP_8_NMVOC": "Emissions",
    "NAEI_SNAP_9_NMVOC": "Emissions",
    "NAEI_SNAP_10_NMVOC": "Emissions",
    "NAEI_SNAP_11_NMVOC": "Emissions",
    "NAEI_SNAP_1_PM10": "Emissions",
    "NAEI_SNAP_2_PM10": "Emissions",
    "NAEI_SNAP_3_PM10": "Emissions",
    "NAEI_SNAP_4_PM10": "Emissions",
    "NAEI_SNAP_5_PM10": "Emissions",
    "NAEI_SNAP_6_PM10": "Emissions",
    "NAEI_SNAP_7_PM10": "Emissions",
    "NAEI_SNAP_8_PM10": "Emissions",
    "NAEI_SNAP_9_PM10": "Emissions",
    "NAEI_SNAP_10_PM10": "Emissions",
    "NAEI_SNAP_11_PM10": "Emissions",
    "NAEI_SNAP_1_PM25": "Emissions",
    "NAEI_SNAP_2_PM25": "Emissions",
    "NAEI_SNAP_3_PM25": "Emissions",
    "NAEI_SNAP_4_PM25": "Emissions",
    "NAEI_SNAP_5_PM25": "Emissions",
    "NAEI_SNAP_6_PM25": "Emissions",
    "NAEI_SNAP_7_PM25": "Emissions",
    "NAEI_SNAP_8_PM25": "Emissions",
    "NAEI_SNAP_9_PM25": "Emissions",
    "NAEI_SNAP_10_PM25": "Emissions",
    "NAEI_SNAP_11_PM25": "Emissions",
}



transportColumns = [
    "Bicycle_Score",
    "Car_and_Taxi_Score",
    "Bus_and_Coach_Score",
    "LGV_Score",
    "HGV_Score",
]

osmRoadInfrastructure = [
    "Road_Infrastructure_Distance_Residential",
    "Road_Infrastructure_Distance_Footway",
    "Road_Infrastructure_Distance_Service",
    "Road_Infrastructure_Distance_Primary",
    "Road_Infrastructure_Distance_Path",
    "Road_Infrastructure_Distance_Cycleway",
    "Road_Infrastructure_Distance_Tertiary",
    "Road_Infrastructure_Distance_Secondary",
    "Road_Infrastructure_Distance_Unclassified",
    "Road_Infrastructure_Distance_Trunk",
    "Road_Infrastructure_Distance_Track",
    "Road_Infrastructure_Distance_Motorway",
    "Road_Infrastructure_Distance_Pedestrian",
    "Road_Infrastructure_Distance_Living_Street",
    "Total_Length_Cycleway",
    "Total_Length_Footway",
    "Total_Length_Living_Street",
    "Total_Length_Motorway",
    "Total_Length_Path",
    "Total_Length_Pedestrian",
    "Total_Length_Primary",
    "Total_Length_Residential",
    "Total_Length_Secondary",
    "Total_Length_Service",
    "Total_Length_Tertiary",
    "Total_Length_Track",
    "Total_Length_Trunk",
    "Total_Length_Unclassified",
]

geographicColumns = [
    "No_Land",
    "Broadleaved_woodland",
    "Coniferous_Woodland",
    "Arable_and_Horticulture",
    "Improved_Grassland",
    "Neutral_Grassland",
    "Calcareous_Grassland",
    "Acid_grassland",
    "Fen_Marsh_and_Swamp",
    "Heather",
    "Heather_grassland",
    "Bog",
    "Inland_Rock",
    "Saltwater",
    "Freshwater",
    "Supralittoral_Rock",
    "Supralittoral_Sediment",
    "Littoral_Rock",
    "Littoral_sediment",
    "Saltmarsh",
    "Urban",
    "Suburban",
]

metrologicalColumns = [
    "U_Component_of_Wind_100m",
    "V_Component_of_Wind_100m",
    "U_Component_of_Wind_10m",
    "V_Component_of_Wind_10m",
    "Dewpoint_Temperature_2m",
    "Temperature_2m",
    "Boundary_Layer_Height",
    "Downward_UV_Radiation_at_the_Surface",
    "Instantaneous_10m_Wind_Gust",
    "Surface_Pressure",
    "Total_Column_Rain_Water",
]

emissionsColumns = [
    "NAEI_SNAP_1_NOx",
    "NAEI_SNAP_2_NOx",
    "NAEI_SNAP_3_NOx",
    "NAEI_SNAP_4_NOx",
    "NAEI_SNAP_5_NOx",
    "NAEI_SNAP_6_NOx",
    "NAEI_SNAP_7_NOx",
    "NAEI_SNAP_8_NOx",
    "NAEI_SNAP_9_NOx",
    "NAEI_SNAP_10_NOx",
    "NAEI_SNAP_11_NOx",
    "NAEI_SNAP_1_CO",
    "NAEI_SNAP_2_CO",
    "NAEI_SNAP_3_CO",
    "NAEI_SNAP_4_CO",
    "NAEI_SNAP_5_CO",
    "NAEI_SNAP_6_CO",
    "NAEI_SNAP_7_CO",
    "NAEI_SNAP_8_CO",
    "NAEI_SNAP_9_CO",
    "NAEI_SNAP_10_CO",
    "NAEI_SNAP_11_CO",
    "NAEI_SNAP_1_SOx",
    "NAEI_SNAP_2_SOx",
    "NAEI_SNAP_3_SOx",
    "NAEI_SNAP_4_SOx",
    "NAEI_SNAP_5_SOx",
    "NAEI_SNAP_6_SOx",
    "NAEI_SNAP_7_SOx",
    "NAEI_SNAP_8_SOx",
    "NAEI_SNAP_9_SOx",
    "NAEI_SNAP_10_SOx",
    "NAEI_SNAP_11_SOx",
    "NAEI_SNAP_1_NH3",
    "NAEI_SNAP_2_NH3",
    "NAEI_SNAP_3_NH3",
    "NAEI_SNAP_4_NH3",
    "NAEI_SNAP_5_NH3",
    "NAEI_SNAP_6_NH3",
    "NAEI_SNAP_7_NH3",
    "NAEI_SNAP_8_NH3",
    "NAEI_SNAP_9_NH3",
    "NAEI_SNAP_10_NH3",
    "NAEI_SNAP_11_NH3",
    "NAEI_SNAP_1_NMVOC",
    "NAEI_SNAP_2_NMVOC",
    "NAEI_SNAP_3_NMVOC",
    "NAEI_SNAP_4_NMVOC",
    "NAEI_SNAP_5_NMVOC",
    "NAEI_SNAP_6_NMVOC",
    "NAEI_SNAP_7_NMVOC",
    "NAEI_SNAP_8_NMVOC",
    "NAEI_SNAP_9_NMVOC",
    "NAEI_SNAP_10_NMVOC",
    "NAEI_SNAP_11_NMVOC",
    "NAEI_SNAP_1_PM10",
    "NAEI_SNAP_2_PM10",
    "NAEI_SNAP_3_PM10",
    "NAEI_SNAP_4_PM10",
    "NAEI_SNAP_5_PM10",
    "NAEI_SNAP_6_PM10",
    "NAEI_SNAP_7_PM10",
    "NAEI_SNAP_8_PM10",
    "NAEI_SNAP_9_PM10",
    "NAEI_SNAP_10_PM10",
    "NAEI_SNAP_11_PM10",
    "NAEI_SNAP_1_PM25",
    "NAEI_SNAP_2_PM25",
    "NAEI_SNAP_3_PM25",
    "NAEI_SNAP_4_PM25",
    "NAEI_SNAP_5_PM25",
    "NAEI_SNAP_6_PM25",
    "NAEI_SNAP_7_PM25",
    "NAEI_SNAP_8_PM25",
    "NAEI_SNAP_9_PM25",
    "NAEI_SNAP_10_PM25",
    "NAEI_SNAP_11_PM25",
]

remoteSensingColumns = [
    "Sentinel_5P_NO2",
    "Sentinel_5P_AAI",
    "Sentinel_5P_CO",
    "Sentinel_5P_HCHO",
    "Sentinel_5P_O3",
]

temporalColumns = [
    "Week_Number",
    "Month_Number",
    "Day_of_Week_Number",
    "Hour_Number",
]


featureVectorSubsets = {
    "All": transportColumns
    + temporalColumns
    + metrologicalColumns
    + remoteSensingColumns
    + osmRoadInfrastructure
    + geographicColumns
    + emissionsColumns,
    "Forecasting": osmRoadInfrastructure
    + geographicColumns
    + metrologicalColumns
    + temporalColumns,
    "Forecasting (Transport and Emissions)": transportColumns
    + osmRoadInfrastructure
    + geographicColumns
    + metrologicalColumns
    + temporalColumns
    + emissionsColumns,
    "Global": temporalColumns + metrologicalColumns + remoteSensingColumns,
    "Temporal": temporalColumns,
    "Metrological": metrologicalColumns,
    "Transport Infrastructure": osmRoadInfrastructure,
    "Transport Use": transportColumns,
    "Remote Sensing": remoteSensingColumns,
    "Geographic": geographicColumns,
    "Emissions": emissionsColumns,
    "Transport Infrastructure Policy": temporalColumns
    + metrologicalColumns
    + osmRoadInfrastructure,
    "Climate Projections": transportColumns
    + temporalColumns
    + metrologicalColumns
    + osmRoadInfrastructure
    + geographicColumns,
}
