name: Black Code Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install "black[jupyter]"

      - name: Run Black Check
        run: black --check .
